#!/usr/bin/env bash
set -Eeuo pipefail

BOREALIS_NETWORKING_DIR="$HOME/borealis_networking"
BOREALIS_NETWORKING_STATE_DIR="$HOME/borealis_networking/borealis_client/state"
SSH_CONFIG_DIR="$HOME/.ssh"
SSH_CONFIG_FILE="$SSH_CONFIG_DIR/config"
SSH_CONFIG_INCLUDE_FILE="$SSH_CONFIG_DIR/config.d/borealis_networking"


setup_local_borealis_networking_dirs() {
  mkdir -p "$BOREALIS_NETWORKING_DIR/shared_fs"
  mkdir -p "$BOREALIS_NETWORKING_STATE_DIR/bin"
  mkdir -p "$SSH_CONFIG_DIR/config.d"

  if [[ ! -f "$SSH_CONFIG_FILE" ]]; then
    touch "$SSH_CONFIG_FILE"
    chmod 600 "$SSH_CONFIG_FILE"
  fi

  if ! grep -q "Include ~/.ssh/config.d/borealis_networking" "$SSH_CONFIG_FILE"; then
    printf '\nInclude ~/.ssh/config.d/borealis_networking\n' >> "$SSH_CONFIG_FILE"
  fi

  write_refresh_script
}


write_refresh_script() {
  cat > "$BOREALIS_NETWORKING_STATE_DIR/bin/borealis-networking-refresh-ssh-aliases" <<'SCRIPT'
#!/usr/bin/env bash
set -Eeuo pipefail

: "${BOREALIS_NETWORKING_SUPERMASTER_URL:=http://100.119.27.108:8080}"

SSH_CONFIG_INCLUDE_FILE="$HOME/.ssh/config.d/borealis_networking"

response="$(curl -fsSL "${BOREALIS_NETWORKING_SUPERMASTER_URL%/}/devices" \
  -H "x-actor: borealis-networking-ssh-alias-refresh")"

{
  echo "# Auto-generated by borealis_networking installer."
  echo "# Do not edit manually."

  echo "$response" | jq -r '.[] | [(.machine_id // ""), (.hostname // ""), (.tailscale_name // ""), (.assigned_role // "")] | @tsv' | while IFS=$'\t' read -r machine_id hostname tailscale_name assigned_role; do
    if [[ -z "$tailscale_name" || "$tailscale_name" == "null" ]]; then
      continue
    fi

    safe_machine="${machine_id//[^a-zA-Z0-9._-]/-}"
    safe_host="${hostname//[^a-zA-Z0-9._-]/-}"

    echo ""
    echo "Host $safe_machine $safe_host"
    echo "  HostName $tailscale_name"
    echo "  User $USER"
    echo "  IdentitiesOnly yes"
  done
} > "$SSH_CONFIG_INCLUDE_FILE"

chmod 600 "$SSH_CONFIG_INCLUDE_FILE"
SCRIPT
  chmod +x "$BOREALIS_NETWORKING_STATE_DIR/bin/borealis-networking-refresh-ssh-aliases"
}


refresh_ssh_aliases() {
  export BOREALIS_NETWORKING_SUPERMASTER_URL

  "$BOREALIS_NETWORKING_STATE_DIR/bin/borealis-networking-refresh-ssh-aliases" || log_warn "SSH alias refresh failed"

  if ! grep -q "$BOREALIS_NETWORKING_STATE_DIR/bin" <<< ":$PATH:"; then
    log_info "Add this to your shell profile to use helper commands:"
    log_info "  export PATH=\"$BOREALIS_NETWORKING_STATE_DIR/bin:\$PATH\""
  fi
}
