#!/usr/bin/env bash
set -Eeuo pipefail

NETWORKING_DIR="$HOME/networking"
NETWORKING_STATE_DIR="$HOME/.networking"
SSH_CONFIG_DIR="$HOME/.ssh"
SSH_CONFIG_FILE="$SSH_CONFIG_DIR/config"
SSH_CONFIG_INCLUDE_FILE="$SSH_CONFIG_DIR/config.d/networking"


setup_local_networking_dirs() {
  mkdir -p "$NETWORKING_DIR/shared_fs"
  mkdir -p "$NETWORKING_STATE_DIR/bin"
  mkdir -p "$SSH_CONFIG_DIR/config.d"

  if [[ ! -f "$SSH_CONFIG_FILE" ]]; then
    touch "$SSH_CONFIG_FILE"
    chmod 600 "$SSH_CONFIG_FILE"
  fi

  if ! grep -q "Include ~/.ssh/config.d/networking" "$SSH_CONFIG_FILE"; then
    printf '\nInclude ~/.ssh/config.d/networking\n' >> "$SSH_CONFIG_FILE"
  fi

  write_refresh_script
}


write_refresh_script() {
  cat > "$NETWORKING_STATE_DIR/bin/networking-refresh-ssh-aliases" <<'SCRIPT'
#!/usr/bin/env bash
set -Eeuo pipefail

: "${NETWORKING_SUPERMASTER_URL:?NETWORKING_SUPERMASTER_URL is required}"
: "${NETWORKING_API_TOKEN:?NETWORKING_API_TOKEN is required}"

SSH_CONFIG_INCLUDE_FILE="$HOME/.ssh/config.d/networking"

response="$(curl -fsSL "${NETWORKING_SUPERMASTER_URL%/}/devices" \
  -H "x-api-token: ${NETWORKING_API_TOKEN}" \
  -H "x-actor: ssh-alias-refresh")"

{
  echo "# Auto-generated by networking installer."
  echo "# Do not edit manually."

  echo "$response" | jq -r '.[] | [(.machine_id // ""), (.hostname // ""), (.tailscale_name // ""), (.assigned_role // "")] | @tsv' | while IFS=$'\t' read -r machine_id hostname tailscale_name assigned_role; do
    if [[ -z "$tailscale_name" || "$tailscale_name" == "null" ]]; then
      continue
    fi

    safe_machine="${machine_id//[^a-zA-Z0-9._-]/-}"
    safe_host="${hostname//[^a-zA-Z0-9._-]/-}"

    echo ""
    echo "Host $safe_machine $safe_host"
    echo "  HostName $tailscale_name"
    echo "  User $USER"
    echo "  IdentitiesOnly yes"
  done
} > "$SSH_CONFIG_INCLUDE_FILE"

chmod 600 "$SSH_CONFIG_INCLUDE_FILE"
SCRIPT
  chmod +x "$NETWORKING_STATE_DIR/bin/networking-refresh-ssh-aliases"
}


refresh_ssh_aliases() {
  export NETWORKING_SUPERMASTER_URL
  export NETWORKING_API_TOKEN

  "$NETWORKING_STATE_DIR/bin/networking-refresh-ssh-aliases" || log_warn "SSH alias refresh failed"

  if ! grep -q "$NETWORKING_STATE_DIR/bin" <<< ":$PATH:"; then
    log_info "Add this to your shell profile to use helper commands:"
    log_info "  export PATH=\"$NETWORKING_STATE_DIR/bin:\$PATH\""
  fi
}
